Bump MSRV to 1.61
rustls requires it.

```
error: package `rustls v0.21.8` cannot be built because it requires rustc 1.61 or newer, while the currently active rustc version is 1.60.0
```